"""build_lobby: lobby hub model with welcome sign, spawn, treehouse, capsule pads.

map object conventions:
- Workspace.Lobby (Model)
- Workspace.Lobby.SpawnLocation
- 4 capsule pad pairs (8 pads total) tagged LobbyCapsule
  with CapsuleId + CapsulePairId attributes
- BillboardGui over each pad: "Step here to find a buddy"
- treehouse / garden decoration anchor (User 2 grows visuals here)
"""

from __future__ import annotations

from ..lua_emit import (
    LuaProgram,
    add_tag,
    cframe_pos,
    cframe_pos_yaw,
    clear_existing,
    lua_string,
    make_billboard_gui,
    make_model,
    make_part,
    set_attribute,
)
from ..style import PALETTE, Tags, Attributes


# capsule pad colors keyed by pair index
_PAIR_COLORS = [
    PALETTE.capsule_a,
    PALETTE.capsule_b,
    PALETTE.capsule_c,
    PALETTE.capsule_d,
]


def emit_lobby_lua(
    *,
    pair_count: int = 4,
    origin: tuple[float, float, float] = (0, 0, 0),
) -> str:
    """return a complete lua program that builds the lobby."""
    if pair_count < 1 or pair_count > 8:
        raise ValueError("pair_count must be 1..8")

    p = LuaProgram()
    p.comment("buddy bridge lobby — generated by buddy-map-generator")

    ox, oy, oz = origin
    # idempotency: nuke any existing lobby so re-running is safe
    p.line(clear_existing("Workspace", "Lobby"))

    p.line(make_model("lobby", parent="Workspace", name="Lobby"))

    # ground plane — large grassy disc-ish square. cartoon, not realistic
    p.line(
        make_part(
            "ground",
            parent="lobby",
            name="LobbyGround",
            size=(220, 2, 220),
            cframe=cframe_pos(ox, oy - 1, oz),
            color_rgb=PALETTE.grass,
            material_name="Grass",
        )
    )

    # central path that anchors the eye toward the welcome sign
    p.line(
        make_part(
            "path",
            parent="lobby",
            name="WelcomePath",
            size=(10, 0.3, 60),
            cframe=cframe_pos(ox, oy + 0.15, oz - 20),
            color_rgb=PALETTE.path,
            material_name="Sand",
        )
    )

    # spawn location at the south end of the path
    p.line(
        f"local spawn_part = Instance.new(\"SpawnLocation\")\n"
        f"spawn_part.Name = \"LobbySpawn\"\n"
        f"spawn_part.Size = Vector3.new(8, 1, 8)\n"
        f"spawn_part.CFrame = {cframe_pos(ox, oy + 0.5, oz - 50)}\n"
        f"spawn_part.Anchored = true\n"
        f"spawn_part.Material = Enum.Material.SmoothPlastic\n"
        f"spawn_part.Color = {color_palette('capsule_b')}\n"
        f"spawn_part.TopSurface = Enum.SurfaceType.Smooth\n"
        f"spawn_part.Neutral = true\n"
        f"spawn_part.Parent = lobby"
    )

    # welcome sign — a tall friendly board with a billboard above it
    p.line(
        make_part(
            "sign_post_l",
            parent="lobby",
            name="WelcomePost1",
            size=(0.8, 8, 0.8),
            cframe=cframe_pos(ox - 6, oy + 4, oz + 18),
            color_rgb=PALETTE.wood_dark,
            material_name="Wood",
        )
    )
    p.line(
        make_part(
            "sign_post_r",
            parent="lobby",
            name="WelcomePost2",
            size=(0.8, 8, 0.8),
            cframe=cframe_pos(ox + 6, oy + 4, oz + 18),
            color_rgb=PALETTE.wood_dark,
            material_name="Wood",
        )
    )
    p.line(
        make_part(
            "sign_face",
            parent="lobby",
            name="WelcomeBoard",
            size=(13, 4, 0.6),
            cframe=cframe_pos(ox, oy + 6.5, oz + 18),
            color_rgb=PALETTE.sign_face,
            material_name="Wood",
        )
    )
    p.line(
        make_billboard_gui(
            "welcome_gui",
            adornee="sign_face",
            text="Buddy Bridge — Find a buddy and start a run",
            studs_offset_y=4,
            text_size=42,
        )
    )

    # treehouse / garden decorative area — east of the spawn path
    p.line(make_model("treehouse", parent="lobby", name="Treehouse"))
    p.line(
        make_part(
            "th_trunk",
            parent="treehouse",
            name="Trunk",
            size=(5, 18, 5),
            cframe=cframe_pos(ox + 60, oy + 9, oz - 10),
            color_rgb=PALETTE.wood_warm,
            material_name="Wood",
        )
    )
    # rounded canopy via three offset spheres (chunky cartoon)
    for idx, (cx, cy, cz, cs) in enumerate(
        [
            (ox + 60, oy + 22, oz - 10, 14),
            (ox + 56, oy + 24, oz - 14, 10),
            (ox + 64, oy + 24, oz - 6, 10),
        ]
    ):
        p.line(
            make_part(
                f"th_leaf_{idx}",
                parent="treehouse",
                name=f"Canopy{idx}",
                size=(cs, cs, cs),
                cframe=cframe_pos(cx, cy, cz),
                color_rgb=PALETTE.treehouse_leaf,
                material_name="Grass",
                shape="Ball",
            )
        )
    # treehouse cabin perched on the trunk
    p.line(
        make_part(
            "th_cabin",
            parent="treehouse",
            name="Cabin",
            size=(8, 6, 8),
            cframe=cframe_pos(ox + 60, oy + 16, oz - 10),
            color_rgb=PALETTE.wood_warm,
            material_name="WoodPlanks",
        )
    )
    p.created("Treehouse")

    # capsule pads — four pairs, fanned around the welcome path. each pair is
    # spaced 6 studs apart and the pairs orbit a soft arc north of spawn.
    arc_radius = 28
    for pair_idx in range(pair_count):
        # spread pairs across a half circle in front of the welcome sign
        if pair_count == 1:
            angle = 0
        else:
            spread_deg = 120  # pairs span a 120-degree arc
            angle = -spread_deg / 2 + spread_deg * pair_idx / (pair_count - 1)
        import math

        ang_rad = math.radians(angle)
        cx = ox + math.sin(ang_rad) * arc_radius
        cz = oz + 0 + (-math.cos(ang_rad) * arc_radius)
        pair_color = _PAIR_COLORS[pair_idx % len(_PAIR_COLORS)]

        # pair signage — tiny archway label
        p.line(
            make_part(
                f"arch_{pair_idx}",
                parent="lobby",
                name=f"PairArch{pair_idx + 1}",
                size=(7, 0.6, 0.6),
                cframe=cframe_pos(cx, oy + 8, cz),
                color_rgb=PALETTE.wood_dark,
                material_name="Wood",
            )
        )
        p.line(
            make_part(
                f"arch_l_{pair_idx}",
                parent="lobby",
                name=f"PairArchPostL{pair_idx + 1}",
                size=(0.5, 8, 0.5),
                cframe=cframe_pos(cx - 3.5, oy + 4, cz),
                color_rgb=PALETTE.wood_dark,
                material_name="Wood",
            )
        )
        p.line(
            make_part(
                f"arch_r_{pair_idx}",
                parent="lobby",
                name=f"PairArchPostR{pair_idx + 1}",
                size=(0.5, 8, 0.5),
                cframe=cframe_pos(cx + 3.5, oy + 4, cz),
                color_rgb=PALETTE.wood_dark,
                material_name="Wood",
            )
        )
        p.line(
            make_billboard_gui(
                f"arch_label_{pair_idx}",
                adornee=f"arch_{pair_idx}",
                text=f"Buddy Pair {pair_idx + 1}",
                studs_offset_y=2,
                text_size=32,
            )
        )

        # the two pads sit east+west of the arch center, 6 studs apart
        for side_idx, side_letter in enumerate(("a", "b")):
            offset = -3 if side_idx == 0 else 3
            pad_var = f"pad_{pair_idx}_{side_letter}"
            p.line(
                make_part(
                    pad_var,
                    parent="lobby",
                    name=f"CapsulePad_{pair_idx + 1}{side_letter.upper()}",
                    size=(6, 1, 6),
                    cframe=cframe_pos(cx + offset, oy + 0.5, cz),
                    color_rgb=pair_color,
                    material_name="SmoothPlastic",
                    shape="Cylinder",
                )
            )
            p.line(add_tag(pad_var, Tags.LOBBY_CAPSULE))
            p.line(
                set_attribute(
                    pad_var,
                    Attributes.CAPSULE_ID,
                    f"capsule_{pair_idx + 1}{side_letter}",
                )
            )
            p.line(
                set_attribute(
                    pad_var,
                    Attributes.CAPSULE_PAIR_ID,
                    f"pair_{pair_idx + 1}",
                )
            )
            p.line(
                make_billboard_gui(
                    f"{pad_var}_gui",
                    adornee=pad_var,
                    text="Step here to find a buddy",
                    studs_offset_y=3,
                    text_size=22,
                )
            )
            p.created(f"CapsulePad_{pair_idx + 1}{side_letter.upper()}")

    p.note(f"lobby built with {pair_count} capsule pair(s)")
    return p.render()


def color_palette(field_name: str) -> str:
    """small accessor used inside f-strings — keeps lua emission readable."""
    rgb = getattr(PALETTE, field_name)
    return f"Color3.fromRGB({rgb[0]}, {rgb[1]}, {rgb[2]})"


# unused names import below silenced — keep them so callers get one
# import line: `from .lobby import emit_lobby_lua`
__all__ = ["emit_lobby_lua"]
_ = (cframe_pos_yaw, lua_string)  # imported for parity with sibling tools
